Правда или действие
htmlacademy-univer-javascript-1/2430625-kekstagram-4 pull request #8
Opened 2023-11-27 14:11 UTC by nenichv

2023-12-01 14:15 UTC, MaksimovG requested changes

2023-12-01 14:15 UTC, MaksimovG commented on js/main.js
> +import './validation.js';
вот прям сходу - неверно. так модули не подключаются

2023-12-01 14:15 UTC, MaksimovG commented on js/main.js
> +import './validation.js';
в модуле должны быть ручки (функции) которые его запускают или отменяют

2023-12-04 14:18 UTC, MaksimovG requested changes

2023-12-04 14:18 UTC, MaksimovG commented on js/main.js
> +formValidation();
не относится к этой работе, вызывается не в том месте где нужно вызывать

2023-12-04 14:18 UTC, MaksimovG commented on js/validation.js
> +const Error = {
константы идут перед основным кодом.

2023-12-04 14:18 UTC, MaksimovG commented on js/validation.js
> +function onFormSubmit (evt) {
почему function

2023-12-04 14:18 UTC, MaksimovG commented on js/validation.js
> +};
событие change должно открыть попап,  и уже функция открывающая попап должна наложить сопутствующие обработчики

2023-12-04 16:11 UTC, MaksimovG requested changes

2023-12-04 16:11 UTC, MaksimovG commented on index.html
> +                    <input class="effect-level__value" type="number" step="any" name="effect-level" value="" placeholder="red" >
а зачем вот это?

2023-12-04 16:11 UTC, MaksimovG commented on index.html
>    <script type="module" src ='js/main.js'></script>
пробелы

2023-12-04 16:11 UTC, MaksimovG commented on index.html
> +  <script src='pristine/pristine.min.js'></script>
vendor/pristine.min.js

2023-12-04 16:11 UTC, MaksimovG commented on js/validation.js
> +});
обарботчики анонимные, обработчики накладываются в потоке и нигде не снимаются

2023-12-04 16:11 UTC, MaksimovG commented on js/validation.js
> +const hideWindow = () => {
название не соответствует логике

2023-12-04 16:11 UTC, MaksimovG commented on js/validation.js
> +рristine.addValidator(hashtag, isOriginalTag, Error.UNORIGINALITY, 1, true);
надо попробовать обернуть в функцию

2023-12-04 16:11 UTC, MaksimovG commented on js/validation.js
> +  fileInput.addEventListener('change', onOpenModalWindow);
onFileInputChange

2023-12-05 17:18 UTC, nenichv commented on index.html
> +                    <input class="effect-level__value" type="number" step="any" name="effect-level" value="" placeholder="red">
оставила пока placeholder="red", тк ошибка в html-файле

2023-12-07 07:18 UTC, MaksimovG approved these changes

2023-12-07 07:18 UTC, MaksimovG commented on index.html
>    <script type="module" src ='js/main.js'></script>
внимательнее

2023-12-07 07:18 UTC, MaksimovG commented on index.html
> +                    <input class="effect-level__value" type="number" step="any" name="effect-level" value="" placeholder="red">
не placeholder="" тоже ругается?

2023-12-07 07:18 UTC, merged

2023-12-07 07:34 UTC, nenichv commented on index.html
> +                    <input class="effect-level__value" type="number" step="any" name="effect-level" value="" placeholder="red">
да. не знаю почему